#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/* automatically generated by rust-bindgen */

extern "C" {
    pub fn fstReaderClose(ctx: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn fstReaderOpen(nam: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void;
}
